CREATE TABLE LOCALIZZATORE_SESSION 
	(IDMAP VARCHAR2(100), DATA DATE, CONNSTRING VARCHAR2(100), MAPNAME VARCHAR2(50), MAPDESCRIPTION BLOB, IMAGEDISPLAY BLOB, SIMBOLOGIA BLOB DEFAULT NULL,
	 CONSTRAINT PK_LOCALIZZATORE_SESSION primary key (IDMAP)
	);
	
CREATE TABLE NORMALIZZATORE_SESSION
	(HANDLE VARCHAR2(100), DATA DATE, NORMALIZZATORESOAPPORT BLOB,
	 CONSTRAINT PK_NORMALIZZATORE_SESSION primary key (HANDLE)
	);
	
CREATE TABLE SDE_SESSION
	(IDLRS VARCHAR2(100), DATA DATE, UTENTE VARCHAR2(50), PWD VARCHAR2(50), CONNSTRING VARCHAR2(100), ROADLAYER VARCHAR2(50), GEOMETRYCOL VARCHAR2(50), IDCOL VARCHAR2(50),
	 CONSTRAINT PK_SDE_SESSION primary key (IDLRS)
	);
	